{
 "title": "Cert-Manager",
 "tags": [
  "Certificates",
  "Jetstack"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(kube_namespace_created, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Left",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(sort_desc(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$Namespace\"})-time()) by (namespace, name)"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status{namespace=~\"$Namespace\"}) BY (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "max(sort_desc(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$Namespace\"})-time()) by (namespace, name)",
     "legendFormat": " {{namespace}} / {{name}}"
    }
   ]
  },
  { "title": "ACME Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Overall requests per 2m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)"
    }
   ]
  },
  {
   "title": "/directory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/directory\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/cert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/cert\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/new-acct",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-acct\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/order",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/order\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/new-order",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-order\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/authz-v3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/authz-v3\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/chall-v3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/chall-v3\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/finalize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/finalize\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}