{
 "title": "Drone CI",
 "tags": [
  "drone",
  "drone-ci",
  "ci/cd"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Builds",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "drone_build_count" }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "drone_running_jobs", "legendFormat": "Running" },
    { "expr": "drone_pending_jobs", "legendFormat": "Pending" }
   ]
  },
  {
   "title": "Builds",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "drone_running_builds", "legendFormat": "Running" },
    { "expr": "drone_pending_builds", "legendFormat": "Pending" }
   ]
  },
  {
   "title": "Activated Repos",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "drone_repo_count" }
   ]
  },
  {
   "title": "Total Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "drone_user_count" }
   ]
  },
  {
   "title": "Agent CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"(.*)+agent(.*)+\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Agent network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"(.*)+agent(.*)+\"}[1m])) by (pod)",
     "legendFormat": "RX: {{ pod}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",name=~\"(.*)+agent(.*)+\"}[1m])) by (pod)",
     "legendFormat": "TX: {{ pod}}"
    }
   ]
  },
  {
   "title": "Agent Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"(.*)+agent(.*)+\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}