{
 "title": "Hass Go Coordinator",
 "tags": [ "home-assistant" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Deepstack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deepstack Analysis Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(deepstack_analysis_latency_ms_sum) / sum(deepstack_analysis_latency_ms_count)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Deepstack Analysis Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(deepstack_analysis_errors[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Blueiris", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Blueiris Image Fetch Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(blueiris_image_fetch_latency_ms_sum) / sum(blueiris_image_fetch_latency_ms_count)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}