{
 "title": "Homelab Hue",
 "tags": [
  "Homelab",
  "Hue"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache Update Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hue_cache_update_latency_ms_sum/hue_cache_update_latency_ms_count",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Cache Update Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(hue_cache_update_errors) by (type, kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}} - {{type}}"
    }
   ]
  },
  {
   "title": "Events Emitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hue_events_emitted[1m])*60",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Lights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "On",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hue_device_state_change{deviceType=\"light\", state=\"on\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reachable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hue_device_state_change{deviceType=\"light\", state=\"reachable\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Battery Levels",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "hue_device_state_change{deviceType=\"sensor\", state=\"battery\", type=\"presence\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "hue_device_state_change{deviceType=\"sensor\", state=\"temperature\", type=\"temperature\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Motion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hue_device_state_change{deviceType=\"sensor\", state=\"presence\", type=\"presence\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Light Level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hue_device_state_change{deviceType=\"sensor\", state=\"light_level\", type=\"light_level\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "On",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hue_device_state_change{deviceType=\"sensor\", state=\"on\", type=\"presence\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reachable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hue_device_state_change{deviceType=\"sensor\", state=\"reachable\", type=\"presence\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}