{
 "title": "Kubernetes Workloads",
 "tags": [
  "kubernetes",
  "workloads",
  "k8s"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployments",
    "query": "label_values(kube_deployment_metadata_generation{namespace=~\"$namespace\"}, deployment)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name=~\"$deployment-\\\\w{5,10}\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores (Masters)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",instance=~\".*master.*\"}[1m]))/sum(kube_node_status_allocatable_cpu_cores{node=~\".*master.*\"}))*100"
    }
   ]
  },
  {
   "title": "Memory (Masters)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",instance=~\".*master.*\"})/sum(kube_node_status_allocatable_memory_bytes{node=~\".*master.*\"}))*100"
    }
   ]
  },
  {
   "title": "Cores (Workers)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",instance=~\".*worker.*\"}[1m]))/sum(kube_node_status_allocatable_cpu_cores{node=~\".*worker.*\"}))*100"
    }
   ]
  },
  {
   "title": "Memory (Workers)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",instance=~\".*worker.*\"})/sum(kube_node_status_allocatable_memory_bytes{node=~\".*worker.*\"}))*100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",instance=~\".*master.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\".*master.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",instance=~\".*master.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\".*master.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",instance=~\".*worker.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\".*worker.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",instance=~\".*worker.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\".*worker.*\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])",
     "legendFormat": "{{ pod }} ({{ container }})"
    }
   ]
  },
  {
   "title": "Throttled CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "\rrate(container_cpu_cfs_throttled_seconds_total{image!=\"\",container!=\"POD\",namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[1m])",
     "legendFormat": "{{ pod }} ({{ container }})"
    }
   ]
  },
  {
   "title": "Percent of Limit Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}))*100"
    }
   ]
  },
  {
   "title": "Pods Missing Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})-(count(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Cores Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Limit Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\", image!=\"\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}))*100"
    }
   ]
  },
  {
   "title": "Pods Missing Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})-(count(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Core Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image!=\"\",container!=\"POD\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{ pod }} ({{ container }})"
    }
   ]
  },
  {
   "title": "Pods Missing Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})-(count(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Limit Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})) * 100"
    }
   ]
  },
  {
   "title": "Pods Missing Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})-(count(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{interface=\"eth0\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"POD\"}[1m])",
     "legendFormat": "RX ({{ pod }})"
    },
    {
     "expr": "0-rate(container_network_transmit_bytes_total{interface=\"eth0\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"POD\"}[1m])",
     "legendFormat": "TX ({{ pod }})"
    }
   ]
  },
  {
   "title": "Total Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface=\"eth0\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"POD\"}[1m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "0-sum(rate(container_network_transmit_bytes_total{interface=\"eth0\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"POD\"}[1m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_dropped_total{interface=\"eth0\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"POD\"}[1m])",
     "legendFormat": "RX ({{ pod }})"
    },
    {
     "expr": "0-rate(container_network_transmit_packets_dropped_total{interface=\"eth0\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"POD\"}[1m])",
     "legendFormat": "TX ({{ pod }})"
    }
   ]
  },
  {
   "title": "Packet Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_errors_total{interface=\"eth0\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"POD\"}[1m])",
     "legendFormat": "RX ({{ pod }})"
    },
    {
     "expr": "0-rate(container_network_transmit_errors_total{interface=\"eth0\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"POD\"}[1m])",
     "legendFormat": "TX ({{ pod }})"
    }
   ]
  }
 ]
}