{
 "title": "Kubernetes Resources",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployments",
    "query": "label_values(kube_deployment_metadata_generation{namespace=~\"$namespace\"}, deployment)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name=~\"$deployment-\\\\w{5,10}\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Quick View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Current CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Throttled CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\rrate(container_cpu_cfs_throttled_seconds_total{image!=\"\",container!=\"POD\",namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[5m])) \rby (container_name)",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Percent of Limit Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}))*100",
     "legendFormat": "Percent of Limit"
    }
   ]
  },
  {
   "title": "Pods Missing Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})-count(rate(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cores Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Current Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\", image!=\"\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}))*100"
    }
   ]
  },
  {
   "title": "Pods Missing Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})-count(rate(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m]))"
    }
   ]
  },
  {
   "title": "Core Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } }
 ]
}