{
 "title": "NATS Server",
 "tags": [
  "NATS",
  "Events"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_cpu", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_mem", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(gnatsd_varz_in_bytes[2m])",
     "legendFormat": "RX: {{kubernetes_pod_name}}"
    },
    {
     "expr": "increase(gnatsd_varz_out_bytes[2m])",
     "legendFormat": "TX: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Message Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gnatsd_varz_in_msgs[2m])",
     "legendFormat": "In: {{kubernetes_pod_name}}"
    },
    {
     "expr": "increase(gnatsd_varz_out_msgs[2m])",
     "legendFormat": "Out: {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_connections", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_subscriptions", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_slow_consumers", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  }
 ]
}