{
 "title": "OpenEBS Pools",
 "tags": [
  "OpenEBS",
  "Pools"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Pool",
    "query": "label_values(openebs_pool_status, openebs_io_storage_pool_claim)"
   },
   {
    "name": "Replica",
    "query": "label_values(openebs_replica_status, openebs_io_cstor_pool)"
   },
   {
    "name": "Volume",
    "query": "label_values(openebs_replica_status{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\"}, vol)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Status",
   "type": "singlestat",
   "description": "Status of pool (0, 1, 2, 3, 4, 5, 6) = {\"Offline\", \"Online\", \"Degraded\", \"Faulted\", \"Removed\", \"Unavail\", \"NoPoolsAvailable\"}",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_pool_status{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\"}"
    }
   ]
  },
  {
   "title": "Replica Rebuilding Status",
   "type": "singlestat",
   "description": "Status of rebuild on replica (0, 1, 2, 3, 4, 5, 6)= {\"INIT\", \"DONE\", \"SNAP REBUILD INPROGRESS\", \"ACTIVE DATASET REBUILD INPROGRESS\",       \"ERRORED\", \"FAILED\", \"UNKNOWN\"}",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_rebuild_status{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Replica Total Rebuild Done Count",
   "type": "singlestat",
   "description": "Total no of rebuild performed",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_total_rebuild_done{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Available Pool Size",
   "type": "singlestat",
   "description": "Available size of pool from zfs list",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_replica_available_size{name!~\".*pvc.*\", openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Used Pool Size",
   "type": "singlestat",
   "description": "Used size of pool from zfs list",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_replica_used_size{name!~\".*pvc.*\", openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Used Pool Size by Replica",
   "type": "singlestat",
   "description": "Used size of pool by replica from zfs list",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_replica_used_size{name=~\".*pvc.*\", openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", name=~\".*/$Volume\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Replica Status",
   "type": "singlestat",
   "description": "Status of replica (0, 1, 2, 3) = {\"Offline\", \"Healthy\", \"Degraded\", \"Rebuilding\"}",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_replica_status{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "Replica Total Rebuild Failed Count",
   "type": "singlestat",
   "description": "Total no of rebuild performed which are failed",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_total_failed_rebuild{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}"
    }
   ]
  },
  {
   "title": "IO's count",
   "type": "graph",
   "description": "Read / Write / Sync IO's",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openebs_total_write_count{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "openebs_total_read_count{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "openebs_sync_count{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}",
     "legendFormat": "Sync"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Write latency on replica",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_write_latency{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}[2m])/increase(openebs_write_block_count{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}[2m])",
     "legendFormat": "Write"
    },
    {
     "expr": "increase(openebs_read_latency{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}[2m])/increase(openebs_read_block_count{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}[2m])",
     "legendFormat": "Read"
    },
    {
     "expr": "increase(openebs_sync_latency{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}[2m])/increase(openebs_sync_count{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}[2m])",
     "legendFormat": "Sync"
    }
   ]
  },
  {
   "title": "IO's in bytes",
   "type": "graph",
   "description": "Read / Write / Sync io's in bytes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "openebs_total_write_bytes{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "openebs_total_read_bytes{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "openebs_rebuild_bytes{openebs_io_storage_pool_claim=\"$Pool\", openebs_io_cstor_pool=\"$Replica\", vol=\"$Volume\"}",
     "legendFormat": "Rebuild"
    }
   ]
  }
 ]
}