{
 "title": "OpenEBS Volumes",
 "tags": [
  "OpenEBS",
  "Volumes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "OpenEBS",
    "label": "OpenEBS Volume",
    "query": "label_values(openebs_size_of_volume, openebs_io_persistent_volume_claim)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Elapsed time since Volume was provisioned",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_uptime{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}/60"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "singlestat",
   "description": "Capacity Used by the Volume",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_size_of_volume{openebs_io_persistent_volume_claim=~\"$OpenEBS\"}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_actual_used{openebs_io_persistent_volume_claim=~\"$OpenEBS\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "description": "IOPS",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_reads{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{Reads}}"
    },
    {
     "expr": "increase(openebs_writes{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{Writes}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Throughput",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(openebs_total_read_bytes{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{Read Throughput}}"
    },
    {
     "expr": "irate(openebs_total_write_bytes{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{Write Throughput}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Latency",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "((increase(openebs_read_time{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}[1m]))/(increase(openebs_reads{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}[1m])))",
     "legendFormat": "{{Read Latency}}"
    },
    {
     "expr": "((increase(openebs_write_time{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}[1m]))/(increase(openebs_writes{job=\"kubernetes-pods\", openebs_io_persistent_volume_claim=~\"$OpenEBS\"}[1m])))",
     "legendFormat": "{{Write Latency}}"
    }
   ]
  }
 ]
}